### ISSUE TITLE
Batalha pode entrar em loop infinito

### ISSUE THREAD

**Issue by caburu** [pauloloppes/Trabalho1POO#1]
Jogando o jogo na sequência abaixo, o método Jogo.batalha() entra em loop infinito.
- Começar o jogo e ir sempre para leste (tentando entrar em todos os lugares). Chegando na biblioteca ir norte e entrar no banco.
- Avaliando o código o problema é que o jogador está sem munição e o terrorista sem arma. Então eles tentam se atacar mas nunca termina.

**Comment by pauloloppes** [comment]
Corrigido. Agora Terrorista e Agente geram dano mesmo estando sem arma, simulando combate mão-a-mão. A batalha sempre termina com um dos dois incapacitado.
