### ISSUE TITLE
Itens tratados de modo não orientado a objetos

### ISSUE THREAD

**Issue by caburu** [pauloloppes/Trabalho1POO#2]
As classes Ambiente e Agente têm internamente objetos do supertipo Item mas recebem e retornam itens através de vetores de strings (o mesmo acontece com terroristas na classe Ambiente). Tal estratégia fere o conceito de Orientação a Objetos, pois os dados que representam os itens (e terroristas) estão sendo passados/recebidos sem estarem representados como objetos.

**Comment by pauloloppes** [comment]
Corrigido.
Toda manipulação de itens é feita passando/retornando instâncias do tipo Item ou subtipos.
