### ISSUE TITLE
UML: Agregação implementada como composição

### ISSUE THREAD

**Issue by caburu** [pauloloppes/Trabalho1POO#3]
O diagrama de classes mostra que o relacionamento de Ambiente e Item é de agregação (o que seria realmente o correto), mas o código na verdade implementa composição.
Obs: parece ser uma consequência do que foi levantado na Issue #2.

**Comment by pauloloppes** [comment]
Corrigido.
Issue #2 foi corrigida, então o código está implementando o relacionamento mostrado no diagrama.
