### ISSUE TITLE
Coesão do método Jogo.criarAmbientes

### ISSUE THREAD

**Issue by caburu** [pauloloppes/Trabalho1POO#5]
O método Jogo.criarAmbientes possui baixa coesão.

**Comment by pauloloppes** [comment]
Corrigido.
O método agora lê um arquivo texto com todas as informações sobre os ambientes, e dependendo do tipo de informação que ele lê, ele chama um método que trata dessa informação.
Ex.: Arquivo fala que está lendo um novo ambiente, criarAmbientes() chama um método que cria um novo ambiente. Arquivo fala que está lendo os itens de determinado ambiente, criarAmbientes() chama um método que lê os itens e os adiciona no ambiente referenciado.
