### ISSUE TITLE
UML: relacionamentos não apresentados

### ISSUE THREAD

**Issue by caburu** [pauloloppes/Trabalho1POO#6]
Há relacionamentos não apresentados no diagrama de classes.
* Exemplo: a classe ambiente cria um objeto da classe Chave, mas esse relacionamento não é mostrado no diagrama.

**Comment by pauloloppes** [comment]
Corrigido.
Foram adicionados os relacionamentos de associação que Agente e Jogo tinham/passaram a ter com os subtipos de Item. Ambiente só trata objetos da superclasse agora.
